version: "3"
services:
  specialty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "specialty"
    # ports:
    #   - "80:80"
    volumes:
      - ./docker/nginx/conf.d/specialty.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: 'taiki-web.ninsan.mydns.jp'
    restart: always

networks:
  default:
    external: true
    name: taiki-network
