version: "3"
services:
  taiki-specialty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "taiki-specialty"
    # ports:
    #   - "80:80"
    volumes:
      - ./etc/nginx/conf.d/taiki-specialty.conf:/etc/nginx/conf.d/taiki-specialty.conf
    environment:
      VIRTUAL_HOST: 'taiki-web.ninsan.mydns.jp'
    restart: always

networks:
  default:
    external: true
    name: sample-network
